import * as Episodes from "../models/Episodes/AllEpisodes";
import { Moment } from "../models/Moments/Moment";
import * as ButtonAssets from "../assets/Buttons/Index/ButtonAssetsIndex";
import { Episode } from "../models/Episode";
import { EpisodeType } from "../models/enums/EpisodeType";

export const ButtonMoments: Moment[] = new Array(
    new Moment("", Episodes.GetOffTheRails(63), 772, [], [], ButtonAssets.EarliestButton),
    new Moment("", Episodes.GetOffTheRails(63), 905, [], [], ButtonAssets.EarliestButton),
    new Moment("", Episodes.GetOffTheRails(63), 4649, [], [], ButtonAssets.EarliestButton),
    new Moment("", Episodes.GetOffTheRails(63), 4771, [], [], ButtonAssets.EarliestButton),
    new Moment("", Episodes.GetOffTheRails(63), 11991, [], [], ButtonAssets.EarliestButton),
    new Moment("", Episodes.GetAfterDark(97), 2572, [], []),
    new Moment("St. Paddy's 2023", Episodes.GetAfterDark(98), 9155, [], []),
    new Moment("", Episodes.GetH3TV(69),3813, [], [] ),
    new Moment("", Episodes.GetOffTheRails(66), 5029, [], []),
    new Moment("", Episodes.GetH3TV(72), 1538, [], []),
    new Moment("", Episodes.GetH3TV(72), 10673, [], []),
    new Moment("", Episodes.GetLeftovers(45), 4181, [], []),
    new Moment("", Episodes.GetLeftovers(45), 4320, [], []),
    new Moment("", Episodes.GetH3TV(73), 6766, [], []),
    new Moment("", Episodes.GetOffTheRails(70), 252, [], []),
    new Moment("Audio Issues", Episodes.GetAfterDark(104), 1915, [], []),
    new Moment("", Episodes.GetOffTheRails(71), 3456, [], []),
    new Moment("", Episodes.GetOffTheRails(71), 5463, [], []),
    new Moment("Just Audio!", Episodes.GetOffTheRails(71), 8357, [], []),
    new Moment("", Episodes.GetLeftovers(48), 5748, [], []),
    new Moment("", Episodes.GetH3TV(78), 9171, [], []),
    new Moment("Jokes are harmless", Episodes.GetAfterDark(107), 6976, [], []),
    new Moment("", Episodes.GetOffTheRails(74), 5051, [], []),
    new Moment("Grace Van Dien", Episodes.GetAfterDark(108), 6768, [], []),
    new Moment("", Episodes.GetAfterDark(109), 5619, [], []),
    new Moment("", Episodes.GetOffTheRails(76), 9746, [], []),
    new Moment("", Episodes.GetOffTheRails(76), 9847, [], []),
    new Moment("", Episodes.GetAfterDark(110), 8356, [], []),
    new Moment("", Episodes.GetH3TV(82), 5507, [], []),
    new Moment("", Episodes.GetH3TV(83), 12749, [], []),
    new Moment("Ad Reset", Episodes.GetAfterDark(112), 3327, [], []),
    new Moment("The Streamy Awards", Episodes.GetH3TV(84), 718, [], []),
    new Moment("", Episodes.GetH3TV(85), 5929, [], []),
    new Moment("", Episodes.GetH3TV(85), 5975, [], []),
    new Moment("", Episodes.GetH3TV(85), 6057, [], []),
    new Moment("", Episodes.GetH3TV(85), 6163, [], []),
    new Moment("", Episodes.GetOffTheRails(80), 2545, [], []),
    new Moment("", Episodes.GetLeftovers(53), 8000, [], []),
    new Moment("", Episodes.GetLeftovers(55), 708, [], []),
    new Moment("", Episodes.GetLeftovers(55), 6563, [], []),
    new Moment("", Episodes.GetOffTheRails(83), 1, [], []),
    new Moment("", Episodes.GetOffTheRails(83), 1535, [], []),
    new Moment("", Episodes.GetOffTheRails(83), 2112, [], []),
    new Moment("", Episodes.GetOffTheRails(84), 8137, [], []),
    new Moment("", Episodes.GetH3TV(90), 4263, [], []),
    new Moment("", Episodes.GetH3TV(90), 6990, [], []),
    new Moment("", Episodes.GetOffTheRails(85), 4280, [], []),
    new Moment("", Episodes.GetAfterDark(120), 13948, [], []),
    new Moment("", Episodes.GetAfterDark(121), 4091, [], []),
    new Moment("At the Dentist", Episodes.GetH3TV(91), 7116, [], []),
    new Moment("", Episodes.GetH3TV(91), 12117, [], []),
    new Moment("", Episodes.GetAfterDark(121), 4085, [], []),
    new Moment("Taylor Swift PPT", Episodes.GetOffTheRails(87), 9633, [], []),
    new Moment("ft. oliver Tree", Episodes.GetAfterDark(122), 8498, [], []),
    new Moment("Oliver Tree's Grift", Episodes.GetAfterDark(122), 8541, [], []),
    new Moment("Drunk Sub-A-Thon", Episodes.GetAfterDark(123), 10146, [], []),
    new Moment("", Episodes.GetAfterDark(123), 26769, [], []),
    new Moment("", Episodes.GetAfterDark(124), 332, [], []),
    new Moment("Mr. Beast", Episodes.GetAfterDark(126), 3214, [], []),
    new Moment("Buttoning C-Man", Episodes.GetAfterDark(126), 13130, [], []),
    new Moment("ft. Donna Klein", Episodes.GetAfterDark(127), 1411, [], []),
    new Moment("Ethan Conspiracy", Episodes.GetAfterDark(128), 1764, [], []),
    new Moment("ft. Whitney Cummings", Episodes.GetAfterDark(128), 2812, [], []),
    new Moment("", Episodes.GetAfterDark(130), 10161, [], []),
    new Moment("", Episodes.GetH3TV(102), 1751, [], []),
    new Moment("", Episodes.GetAfterDark(131), 4193, [], []),
    new Moment("Ducky's Behavior", Episodes.GetH3TV(103), 902, [], []),
    new Moment("Loopy on Lupus!", Episodes.GetH3TV(103), 12272, [], []),
    new Moment("ft. Fidias", Episodes.GetOffTheRails(99), 3188, [], []),
    new Moment("Crew Uniforms", Episodes.GetAfterDark(133), 2647, [], []),
    new Moment("Glitched (cut from VOD)", Episodes.GetOffTheRails(101), 487, [], []),
    new Moment("Dr. Kim", Episodes.GetAfterDark(134), 6508, [], []),
    new Moment("", Episodes.GetH3TV(105), 1026, [], []),
    new Moment("", Episodes.GetH3TV(105), 1059, [], []),
    new Moment("", Episodes.GetH3TV(105), 5204, [], []),
    new Moment("", Episodes.GetH3TV(105), 12862, [], []),
    new Moment("", Episodes.GetH3TV(106), 5794, [], []),
    new Moment("", Episodes.GetH3TV(106), 9962, [], []),
    new Moment("Keffals #1", Episodes.GetAfterDark(137), 8993, [], []),
    new Moment("Keffals #2", Episodes.GetAfterDark(137), 9121, [], []),
    new Moment("", Episodes.GetH3TV(108), 13158, [], []),
    new Moment("", Episodes.GetH3TV(108), 13206, [], []),
    new Moment("Adin Ross", Episodes.GetAfterDark(138), 9145, [], []),
    new Moment("ft. Jeff & Verica", Episodes.GetOffTheRails(106), 3188, [], []),
    new Moment("Gabes Haircut", Episodes.GetAfterDark(139), 2121, [], []),
    new Moment("", Episodes.GetAfterDark(139), 8195, [], []),
    new Moment("Ethan Spoils Dune", Episodes.GetOffTheRails(107), 3828, [], []),
    new Moment("", Episodes.GetOffTheRails(107), 10217, [], []),
    new Moment("Sneako", Episodes.GetAfterDark(140), 3690, [], []),
    new Moment("Hot Jesus", Episodes.GetH3TV(110), 6933, [], []),
    new Moment("", Episodes.GetH3TV(111), 1634, [], []),
    new Moment("", Episodes.GetH3TV(111), 4481, [], []),
    new Moment("", Episodes.GetH3TV(111), 5441, [], []),
    new Moment("", Episodes.GetH3TV(111), 7607, [], []),
    new Moment("Brian Pecker", Episodes.GetAfterDark(142), 10627, [], []),
    new Moment("", Episodes.GetOffTheRails(110), 1824, [], []),
    new Moment("", Episodes.GetH3TV(113), 3469, [], []),
    new Moment("Over Gypsy Rose", Episodes.GetH3TV(113), 4360, [], []),
    new Moment("Richard Simmons", Episodes.GetH3TV(113), 7454, [], []),
    new Moment("Alpha Male Bootcamp", Episodes.GetH3TV(113), 9046, [], []),
    new Moment("Zhererka vs. TikkyTokky", Episodes.GetOffTheRails(111), 4530, [], []),
    new Moment("Tanning Segment #1", Episodes.GetOffTheRails(111), 11718, [], []),
    new Moment("Tanning Segment #2", Episodes.GetOffTheRails(111), 11769, [], []),
    new Moment("Tanning Segment #3", Episodes.GetOffTheRails(111), 12999, [], []),
    new Moment("Philly D", Episodes.GetOffTheRails(111), 13654, [], []),

    new Moment("Philly D", Episodes.GetOffTheRails(111), 13654, [], []),
    new Moment("Philly D", Episodes.GetOffTheRails(111), 13654, [], []),
    new Moment("Philly D", Episodes.GetOffTheRails(111), 13654, [], []),

    new Moment(
        "",
        new Episode("H3 Show #1", "https://www.youtube.com/watch?v=0lt0tTr-lj4", "2024-04-22", [EpisodeType["H3 Show"]]), 
        2492, [], []
    ),
    new Moment(
        "",
        new Episode("H3 Show #1", "https://www.youtube.com/watch?v=0lt0tTr-lj4", "2024-04-22", [EpisodeType["H3 Show"]]), 
        2611, [], []
    ),
    new Moment(
        "House of Dragon",
        new Episode("H3 Show #2", "https://www.youtube.com/watch?v=x2cyP6KJ0Uc", "2024-04-24", [EpisodeType["H3 Show"]]), 
        1044, [], [], ButtonAssets.HouseOfDragon_H3Show2
    ),
    new Moment(
        "Jimmie Lee Revival",
        new Episode("H3 Show #2", "https://www.youtube.com/watch?v=x2cyP6KJ0Uc", "2024-04-24", [EpisodeType["H3 Show"]]), 
        10097, [], [], ButtonAssets.JimmieLeeRevival_H3Show3
    ),
    new Moment(
        "Jimmie Lee Drama",
        new Episode("H3 Show #4", "https://youtu.be/XPR4gCC10jc", "2024-04-29", [EpisodeType["H3 Show"]]), 
        10097, [], []
    ),
)