import { useState } from "react";
import "./IcebergPage.css";
import { Moment } from "../../models/Moments/Moment";
import { Modal } from "../../components/Modals/Modal";
import IcebergGridItem from "./IcebergGridItem";
import AllIcebergLayers from "../../models/IcebergLayers/AllIcebergLayers";

export function IcebergPage() {
  function SetModalData(
    title: string,
    description: string,
    timestamps: Moment[]
  ) {
    setModalTitle(title);
    setModalDescription(description);
    setModalTimestamps(timestamps);
    setModalOpen(true);
  }

  const [modalOpen, setModalOpen] = useState(false);
  const [modalTitle, setModalTitle] = useState("");
  const [modalDescription, setModalDescription] = useState("");
  const [modalTimestamps, setModalTimestamps] = useState(new Array());
  return (
    <>
      <Modal
        title={modalTitle}
        description={modalDescription}
        timeStamps={modalTimestamps}
        isOpen={modalOpen}
        closeModal={setModalOpen}
      />

      <body>
        <div className="gradient-background">
          <div className="page-layout">
            <div className="iceberg-image">
              <div className="layer 1">
                <IcebergGridItem
                  item={AllIcebergLayers.Layer1.FAMILY}
                  SetModalData={SetModalData}
                  row={2}
                  column={3}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer1.FootSoldiers}
                  SetModalData={SetModalData}
                  row={2}
                  column={7}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer1.Frenemies}
                  SetModalData={SetModalData}
                  row={4}
                  column={4}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer1.PeaceAndLove}
                  SetModalData={SetModalData}
                  row={4}
                  column={8}
                ></IcebergGridItem>
              </div>
              <div className="layer 2">
                <IcebergGridItem
                  item={AllIcebergLayers.Layer2.H2Point9}
                  SetModalData={SetModalData}
                  row={1}
                  column={3}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer2.HairlineKing}
                  SetModalData={SetModalData}
                  row={1}
                  column={6}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer2.Lovebot}
                  SetModalData={SetModalData}
                  row={2}
                  column={2}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer2.PrideMinute}
                  SetModalData={SetModalData}
                  row={3}
                  column={5}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer2.ProlapsedAnus}
                  SetModalData={SetModalData}
                  row={3}
                  column={7}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer2.TheJerseyOutlaw}
                  SetModalData={SetModalData}
                  row={4}
                  column={2}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer2.UncleGabe}
                  SetModalData={SetModalData}
                  row={5}
                  column={6}
                ></IcebergGridItem>
              </div>
              <div className="layer 3">
                <IcebergGridItem
                  item={AllIcebergLayers.Layer3.AUDIOAUDIOAUDIO}
                  SetModalData={SetModalData}
                  row={2}
                  column={2}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer3.DansMouse}
                  SetModalData={SetModalData}
                  row={1}
                  column={4}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer3.EthanIs42}
                  SetModalData={SetModalData}
                  row={1}
                  column={7}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer3.FLOCKA}
                  SetModalData={SetModalData}
                  row={2}
                  column={6}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer3.FivePercent}
                  SetModalData={SetModalData}
                  row={3}
                  column={4}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer3.MajorityFemaleAudience}
                  SetModalData={SetModalData}
                  row={3}
                  column={8}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer3.ScorpionChair}
                  SetModalData={SetModalData}
                  row={4}
                  column={5}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer3.ShoutoutToHisFamily}
                  SetModalData={SetModalData}
                  row={4}
                  column={1}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer3.SteamyAwards}
                  SetModalData={SetModalData}
                  row={5}
                  column={2}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer3.TrillerLawsuits}
                  SetModalData={SetModalData}
                  row={5}
                  column={6}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer3.WAN}
                  SetModalData={SetModalData}
                  row={4}
                  column={7}
                ></IcebergGridItem>
              </div>
              <div className="layer 4">
                <IcebergGridItem
                  item={AllIcebergLayers.Layer4.ABBoxingMatches}
                  SetModalData={SetModalData}
                  row={3}
                  column={2}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer4.ABsBurrito}
                  SetModalData={SetModalData}
                  row={1}
                  column={4}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer4.BombThreats}
                  SetModalData={SetModalData}
                  row={1}
                  column={7}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer4.DrIdz}
                  SetModalData={SetModalData}
                  row={2}
                  column={6}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer4.GodFatherImpression}
                  SetModalData={SetModalData}
                  row={4}
                  column={4}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer4.JokerBrain}
                  SetModalData={SetModalData}
                  row={3}
                  column={8}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer4.PAndP}
                  SetModalData={SetModalData}
                  row={3}
                  column={5}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer4.TwentyBillionDollarCompound}
                  SetModalData={SetModalData}
                  row={2}
                  column={1}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer4.WeightsInFish}
                  SetModalData={SetModalData}
                  row={5}
                  column={2}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer4.ZillyZonka}
                  SetModalData={SetModalData}
                  row={5}
                  column={6}
                ></IcebergGridItem>
              </div>
              <div className="layer 5">
                <IcebergGridItem
                  item={AllIcebergLayers.Layer5.DoesRyanKavanaughLookLikeHarvey}
                  SetModalData={SetModalData}
                  row={1}
                  column={1}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer5.ApologyPodium}
                  SetModalData={SetModalData}
                  row={1}
                  column={5}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer5.BeautifulWorld}
                  SetModalData={SetModalData}
                  row={1}
                  column={9}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer5.ChestnutGate}
                  SetModalData={SetModalData}
                  row={2}
                  column={2}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer5.EthanKleinBodyDouble}
                  SetModalData={SetModalData}
                  row={2}
                  column={7}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer5.Lou}
                  SetModalData={SetModalData}
                  row={3}
                  column={1}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer5.RKellyPassports}
                  SetModalData={SetModalData}
                  row={3}
                  column={4}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer5.SaudiBenefactor}
                  SetModalData={SetModalData}
                  row={3}
                  column={5}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer5.ThatsNotFraud}
                  SetModalData={SetModalData}
                  row={4}
                  column={2}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer5.TheChewZone}
                  SetModalData={SetModalData}
                  row={4}
                  column={7}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer5.Throast}
                  SetModalData={SetModalData}
                  row={5}
                  column={5}
                ></IcebergGridItem>
              </div>
              <div className="layer 6">
                <IcebergGridItem
                  item={AllIcebergLayers.Layer6.AndrewTateCeaseAndDesist}
                  SetModalData={SetModalData}
                  row={5}
                  column={6}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer6.ArabWorldNews}
                  SetModalData={SetModalData}
                  row={1}
                  column={4}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer6.BradTheBull}
                  SetModalData={SetModalData}
                  row={1}
                  column={7}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer6.ContentCourt}
                  SetModalData={SetModalData}
                  row={2}
                  column={6}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer6.Craigsmas}
                  SetModalData={SetModalData}
                  row={4}
                  column={4}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer6.DinkDoink}
                  SetModalData={SetModalData}
                  row={3}
                  column={8}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer6.IJustPeedInMyBasement}
                  SetModalData={SetModalData}
                  row={3}
                  column={3}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer6.MayoMemes}
                  SetModalData={SetModalData}
                  row={2}
                  column={2}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer6.TheBanOfEthanKlein}
                  SetModalData={SetModalData}
                  row={5}
                  column={2}
                ></IcebergGridItem>
              </div>
              <div className="layer 7">
                <IcebergGridItem
                  item={AllIcebergLayers.Layer7.AIIan}
                  SetModalData={SetModalData}
                  row={1}
                  column={2}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer7.BullPenisStaff}
                  SetModalData={SetModalData}
                  row={1}
                  column={5}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer7.DeepfakeJayZIntro}
                  SetModalData={SetModalData}
                  row={1}
                  column={8}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer7.EthansFeet}
                  SetModalData={SetModalData}
                  row={2}
                  column={3}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer7.HungerFF}
                  SetModalData={SetModalData}
                  row={2}
                  column={6}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer7.NathanielKlansman}
                  SetModalData={SetModalData}
                  row={4}
                  column={2}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer7.OhNoSamSeder}
                  SetModalData={SetModalData}
                  row={4}
                  column={7}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer7.TheFeedingWindow}
                  SetModalData={SetModalData}
                  row={3}
                  column={6}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer7.TheMolePeople}
                  SetModalData={SetModalData}
                  row={5}
                  column={3}
                ></IcebergGridItem>
              </div>
              <div className="layer 8">
                <IcebergGridItem
                  item={AllIcebergLayers.Layer8.BarefootBrothersDrive}
                  SetModalData={SetModalData}
                  row={5}
                  column={6}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer8.BenAffleckBackTattoo}
                  SetModalData={SetModalData}
                  row={1}
                  column={4}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer8.ButtholeCandle}
                  SetModalData={SetModalData}
                  row={1}
                  column={7}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer8.DDMegaDooDoo}
                  SetModalData={SetModalData}
                  row={2}
                  column={6}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer8.GERDGang}
                  SetModalData={SetModalData}
                  row={4}
                  column={4}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer8.Gatsby}
                  SetModalData={SetModalData}
                  row={3}
                  column={8}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer8.HOTMEMEPhoneNumber}
                  SetModalData={SetModalData}
                  row={3}
                  column={3}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer8.Swami}
                  SetModalData={SetModalData}
                  row={2}
                  column={2}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer8.VapeGodNFT}
                  SetModalData={SetModalData}
                  row={5}
                  column={2}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer8.WendyWilliamsFartgate}
                  SetModalData={SetModalData}
                  row={5}
                  column={6}
                ></IcebergGridItem>
              </div>
              <div className="layer 9">
                {" "}
                <IcebergGridItem
                  item={AllIcebergLayers.Layer9.BelleDelphineSpitJar}
                  SetModalData={SetModalData}
                  row={3}
                  column={3}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer9.Braco}
                  SetModalData={SetModalData}
                  row={1}
                  column={4}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer9.DanHadHair}
                  SetModalData={SetModalData}
                  row={1}
                  column={7}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer9.DrFaddelDeletedSegment}
                  SetModalData={SetModalData}
                  row={2}
                  column={6}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer9.GhostStories}
                  SetModalData={SetModalData}
                  row={4}
                  column={4}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer9.IGottaPeeSoBad}
                  SetModalData={SetModalData}
                  row={3}
                  column={7}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer9.IanTheInternPowerpoints}
                  SetModalData={SetModalData}
                  row={3}
                  column={5}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer9.InspiredByHowardStern}
                  SetModalData={SetModalData}
                  row={2}
                  column={2}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer9.MobilityMary}
                  SetModalData={SetModalData}
                  row={4}
                  column={2}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer9.MrBeastCeaseAndDesist}
                  SetModalData={SetModalData}
                  row={4}
                  column={6}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer9.ZachsLawnShit}
                  SetModalData={SetModalData}
                  row={4}
                  column={8}
                ></IcebergGridItem>
              </div>
              <div className="layer 10">
                <IcebergGridItem
                  item={AllIcebergLayers.Layer10.AnalFissures}
                  SetModalData={SetModalData}
                  row={4}
                  column={6}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer10.CCRCurse}
                  SetModalData={SetModalData}
                  row={1}
                  column={4}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer10.Fatburgs}
                  SetModalData={SetModalData}
                  row={1}
                  column={7}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer10.GoofGang}
                  SetModalData={SetModalData}
                  row={2}
                  column={6}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer10.LeonardKatzman}
                  SetModalData={SetModalData}
                  row={4}
                  column={4}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer10.LilTracyBeef}
                  SetModalData={SetModalData}
                  row={3}
                  column={8}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer10.PatriceWilsonCountdown}
                  SetModalData={SetModalData}
                  row={3}
                  column={3}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer10.SharkysGiftcard}
                  SetModalData={SetModalData}
                  row={2}
                  column={2}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer10.Shoenice}
                  SetModalData={SetModalData}
                  row={5}
                  column={2}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer10.TheBacH3lor}
                  SetModalData={SetModalData}
                  row={5}
                  column={5}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer10.TheRegulaShmegula}
                  SetModalData={SetModalData}
                  row={5}
                  column={7}
                ></IcebergGridItem>
              </div>
              <div className="layer 11">
                {" "}
                <IcebergGridItem
                  item={AllIcebergLayers.Layer11.BertKriescherLostEpisode}
                  SetModalData={SetModalData}
                  row={4}
                  column={6}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer11.BillBurrEpisode1}
                  SetModalData={SetModalData}
                  row={2}
                  column={4}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer11.BlockedByOJSimpson}
                  SetModalData={SetModalData}
                  row={2}
                  column={7}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer11.ChetHanksThreats}
                  SetModalData={SetModalData}
                  row={3}
                  column={5}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer11.TheDrunkStream}
                  SetModalData={SetModalData}
                  row={4}
                  column={4}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer11.TheWildcardsIdentity}
                  SetModalData={SetModalData}
                  row={3}
                  column={8}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer11.TrillerLawsuitLostEpisode}
                  SetModalData={SetModalData}
                  row={3}
                  column={3}
                ></IcebergGridItem>
              </div>
              <div className="layer 12">
                {" "}
                <IcebergGridItem
                  item={AllIcebergLayers.Layer12.CodyPadrino}
                  SetModalData={SetModalData}
                  row={2}
                  column={3}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer12.JohnWilliamKirbyKelley}
                  SetModalData={SetModalData}
                  row={2}
                  column={7}
                ></IcebergGridItem>
                <IcebergGridItem
                  item={AllIcebergLayers.Layer12.VoiceFlamingoR}
                  SetModalData={SetModalData}
                  row={4}
                  column={5}
                ></IcebergGridItem>
              </div>
            </div>
          </div>
        </div>
      </body>

      {/* <Modal /> */}
    </>
  );
}

export default IcebergPage;
