export enum Tag {
  PeaceAndLove,
  Frenemies,
  WikiFeet,
  "Foot Soldiers",
  "Pride Minute",
  "Hairline King",
  Prolapse,
  Steamys,
  Triller,
  "800DPI",
  "Dans Mouse",
  "Five Percent",
  "5%",
  "Scorpion Chair",
  WAN,
  FLOCKA,
  Birthday,
  "Ethans Birthday",
  "Female Audience",
  "Shoutout to his family",
  "AUDIO AUDIO AUDIO",
  "The Crew",
  FAMILY,
  "Uncle Gabe",
  "White Claw Gabe",
  "H2.9",
  "Jimmie Lee",
  "The Jersey Outlaw",
  LoveBot,
}
