export enum Tag {
  PeaceAndLove,
  Frenemies,
  WikiFeet,
  "Foot Soldiers",
  "Pride Minute",
  "Hairline King",
  Prolapse,
  Steamys,
  Triller,
  "800DPI",
  "Dans Mouse",
  "Five Percent",
  "5%",
  "Scorpion Chair",
  WAN,
  FLOCKA,
  Birthday,
  "Ethans Birthday",
  "Female Audience",
  "Shoutout to his family",
  "AUDIO AUDIO AUDIO",
  "The Crew",
  FAMILY,
  "Uncle Gabe",
  "White Claw Gabe",
  "H2.9",
  "Jimmie Lee",
  "The Jersey Outlaw",
  LoveBot,
  "AB Boxing Matches",
  "Joker Brain",
  "ABs Burrito",
  "P & P",
  "Godfather Impression",
  "Weights in Fish",
  "Zilly Zonka",
  "20 Billion Dollar Compound",
  "Dr. Idz",
  "RyanHarvey.com",
  "Lou",
  "Ethan Body Double",
  "Throast",
  "Saudi Benefactor",
  "Chestnut Gate",
  "R Kelly Passport Song",
  "Thats Not Fraud",
  "The Chew Zone",
  "Apology Podium",
  "Mayo Memes",
  "Andrew Tate Cease and Desist",
  "Brad the Bull",
  "Craigsmas",
  "Content Court",
  "I Just Peed in my Basement",
  "Dink Doink",
  "Donnarchs",
  "thebanofethanklein.com",
  "Arab World News",
  "AI Ian",
  "EthansFeet.com",
  "Bull Penis Staff",
  "Nathaniel Klansman",
  "The Feeding Window",
  "Oh no! Sam Seder",
  "The Mole People",
  "HungerFF",
  "Deepfake JayZ Intro",
  "Barefoot Brothers Drive",
  "Ben Afflecks Back Tattoo",
  "Butthole Candle",
  "Gerd Gang",
  "DD Megadoodoo",
  "808-HOT-MEME",
  "Swami",
  "Vape God NFT",
  Gatsby,
  "Wendy Williams Fartgate",
  "Dan Had Hair",
  "Mr. Beast Cease and Desist",
  "Mobility Mary",
  "Braco",
  "Belle Delphine Spit Jar",
  "Ghost Stories",
  "Zachs Lawn Shit",
  "I Gotta Pee So Bad",
  "Inspired by Howard Stern",
  "Dr. Faddel Deleted Segment",
  "Ian the Intern Powerpoints",
  PowerPoint,
  "Patrice Wilson Countdown Stream",
  "The BacH3lor",
  ShoeNice,
  "Shoe Nice",
  "Anal Fissures",
  "Leonardo Katzman",
  "CCR Curse",
  "Lil Tracy Beef",
  "Fatburgs",
  "The Regula Shmegula",
  "Goof Gang",
  "Sharkys Giftcard",
  "Bert Kriesher Lost Episode",
  "Blocked on Twitter by OJ",
  "n******* f******",
  "Chet Hanks Threats",
  "Bill Burr Episode 1",
  "Triller Lawsuit Lost Episode",
  "The Wildcards Identity",
  "John William Kirbey Kelly",
  "Cody Padrino",
  "VoiceFlamingo-R",
  "Beautiful World",
  "Bomb Threats",
  "The Drunk Stream",
  Lore,
}
