create table "public"."test_createdViaUI" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."test_createdViaUI" enable row level security;

CREATE UNIQUE INDEX "test_createdViaUI_pkey" ON public."test_createdViaUI" USING btree (id);

alter table "public"."test_createdViaUI" add constraint "test_createdViaUI_pkey" PRIMARY KEY using index "test_createdViaUI_pkey";

grant delete on table "public"."test_createdViaUI" to "anon";

grant insert on table "public"."test_createdViaUI" to "anon";

grant references on table "public"."test_createdViaUI" to "anon";

grant select on table "public"."test_createdViaUI" to "anon";

grant trigger on table "public"."test_createdViaUI" to "anon";

grant truncate on table "public"."test_createdViaUI" to "anon";

grant update on table "public"."test_createdViaUI" to "anon";

grant delete on table "public"."test_createdViaUI" to "authenticated";

grant insert on table "public"."test_createdViaUI" to "authenticated";

grant references on table "public"."test_createdViaUI" to "authenticated";

grant select on table "public"."test_createdViaUI" to "authenticated";

grant trigger on table "public"."test_createdViaUI" to "authenticated";

grant truncate on table "public"."test_createdViaUI" to "authenticated";

grant update on table "public"."test_createdViaUI" to "authenticated";

grant delete on table "public"."test_createdViaUI" to "service_role";

grant insert on table "public"."test_createdViaUI" to "service_role";

grant references on table "public"."test_createdViaUI" to "service_role";

grant select on table "public"."test_createdViaUI" to "service_role";

grant trigger on table "public"."test_createdViaUI" to "service_role";

grant truncate on table "public"."test_createdViaUI" to "service_role";

grant update on table "public"."test_createdViaUI" to "service_role";


